### ISSUE TITLE
all sign service down

### ISSUE THREAD

**Issue by ckikoo** [LagrangeDev/LagrangeGo#105]
func send(ptr *qqclient.QQClient, target uint32, flag bool, msg message.IMessageElement) {
	if flag {
		fmt.Println("??????????????????")
		fmt.Println(ptr.SendGroupMessage(target, []message.IMessageElement{msg}))
		fmt.Println("??????????????????")
	} else {
		fmt.Println("??????????????????")
		fmt.Println(ptr.SendPrivateMessage(target, []message.IMessageElement{msg}))
		fmt.Println("??????????????????")
	}
}

??????????????????
nil， all sign service down
??????????????????

为什么会这个？？， 麻烦看到后说下如何处理，谢谢

**Comment by ckikoo** [comment]
??????????????????
<nil> all sign service down
??????????????????

**Comment by ckikoo** [comment]
消息是可以正常收到， 但是发送出去就不行

**Comment by Redmomn** [comment]
字面意思，签名服务器关了，等他恢复

**Comment by ckikoo** [comment]
appInfo := auth.AppList["linux"]
	deviceInfo := &auth.DeviceInfo{
		Guid:          "cfcd208495d565ef66e7dff9f98764da",
		DeviceName:    "Lagrange-DCFCD07E",
		SystemKernel:  "Windows 10.0.22631",
		KernelVersion: "10.0.22631",
	}


// 这是用的签名服务器部分，是你们提供的
	QQClient = client.NewClient(0, appInfo["3.2.10-25765"], "https://sign.lagrangecore.org/api/sign/25765")

**Comment by Redmomn** [comment]
这个关了，等恢复

**Comment by ckikoo** [comment]
ERRO[0030] login err: failed to register session: Packet timed out 
为什么会这样呢？

**Comment by ckikoo** [comment]
> ERRO[0030] login err: failed to register session: Packet timed out 为什么会这样呢？

我把旧的sig.bin删掉后，重新扫码又可以了为什么？

**Comment by Redmomn** [comment]
可能是登录过期了
