### ISSUE TITLE
 关于ck失效的问题

### ISSUE THREAD

**Issue by ckikoo** [LagrangeDev/LagrangeGo#128]
我想实现一个功能，qq 好像存在ck失效的问题， 每隔一阶段，需要手动删除签名文件重新扫码, 否则会存在 注册session 超时的可能性，  
````
err = c.Register()
		if err != nil {
			err = fmt.Errorf("failed to register session: %v", err)
			c.errorln(err)
			return err
		}
		这段代码 会存在注册失败。
````
 我想实现api 来清除无效的内容
我这边做个几个简单的接口 /close  关闭
```
func ()
      // 这个接口调用后，手机上还显示linux 登录， 但是服务器没有收到任何消息了
	qq.QQClient.Release()
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("bot closing"))
	os.Remove("sig.bin")
	os.Remove("qrcode.png")
```

/login

func(){
    	// Attempt login asynchronously.
	go func() {
		err := qq.QQClient.Login("", "qrcode.png")
		if err != nil {
			logrus.Errorln("login error:", err)
			return
		}
	}()

	time.Sleep(time.Second)
	if qq.QQClient.Online.Load() {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("bot is running"))
		return
	}

	// Redirect to the QR code image page.
	w.Header().Set("Location", "/img")
	w.WriteHeader(http.StatusFound)
}
}

/img 接口

就是二维码， 扫码，结果出现的二维码，手机上显示却是该二维码已经失效了

这种如何处理啊？  
我看基于该项目实现的go-cq好像也没对这个问题做出处理。

**Comment by Redmomn** [comment]
release()之后会断开和qq服务器的连接，这个时候是下线状态，我这里测试是没有问题的

至于二维码过期，我这也没有遇到，是不是有可能你的浏览器缓存了之前的二维码

**Comment by ckikoo** [comment]
验证码是因为浏览器cache 。。
现在一个问题是 主动调用close ，但是然后重新 重新login 会出现 
ERRO[2024-12-12T23:15:37+08:00]status_api.go:45  
 login error: failed to register session: Packet timed out 
然后那个验证码没出来？ 这种这种如何处理呢？

close的代码
```
	qq.QQClient.Release()
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("bot closing"))
	os.Remove("sig.bin")
	os.Remove("qrcode.png")
````

login的代码 
```
// Attempt login asynchronously.
	go func() {
		err := qq.QQClient.Login("", "qrcode.png")
		if err != nil {
			logrus.Errorln("login error:", err)
			return
		}
	}()

	time.Sleep(time.Second)
	if qq.QQClient.Online.Load() {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("bot is running"))
		return
	}

	// Redirect to the QR code image page.
	w.Header().Set("Location", "/img")
	w.WriteHeader(http.StatusFound)
````
 
 会出现 login error: failed to register session: Packet timed out

**Comment by ckikoo** [comment]
client 是一个全局变量，会在初次加载时，就已经设置好相关的参数 
	appInfo := auth.AppList["linux"]
	deviceInfo := &auth.DeviceInfo{
		GUID:          "cfcd208495d565ef66e7dff9f98764da",
		DeviceName:    "Lagrange-DCFCD07E",
		SystemKernel:  "Windows 10.0.22631",
		KernelVersion: "10.0.22631",
	}

	QQClient = client.NewClient(0, appInfo["3.2.10-25765"], "https://sign.lagrangecore.org/api/sign/25765")
	QQClient.UseDevice(deviceInfo)

**Comment by Redmomn** [comment]
这个我确实看不出来哪里有问题，不过一般导致Packet timed out的都是session过期
建议用最新版的lagrangego，对这部分的错误返回做了一些处理

**Comment by ckikoo** [comment]
emm  
FetchQRCodeDefault err: Packet timed out
FetchQRCodeDefault err: Packet timed out
FetchQRCodeDefault err: Packet timed out

**Comment by ckikoo** [comment]
func Close(w http.ResponseWriter, r *http.Request) {
	qq.QQClient.Release()
	qq.CanAccessAsk.Clear()
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("bot closing"))
	os.Remove("sig.bin")
	os.Remove("qrcode.png")
}

func Login(w http.ResponseWriter, r *http.Request) {

	if qq.QQClient.Online.Load() {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("bot is running"))
		return
	}

	err := qq.QQClient.FastLogin()
	if err != nil {
		os.Remove("sig.bin")
		os.Remove("qrcode.png")
	}

	if qq.QQClient.Online.Load() {
		Status(w, r)
		return
	}

	qrcodePath := "qrcode.png"
	// Attempt login asynchronously.
	go func() {
		png, _, err := qq.QQClient.FetchQRCodeDefault()
		if err != nil {
			fmt.Printf(" FetchQRCodeDefault err: %v\n", err)
			return
		}

		err = os.WriteFile(qrcodePath, png, 0666)
		if err != nil {
			fmt.Printf(" WriteFile err: %v\n", err)
			return
		}

		for {
			retCode, err := qq.QQClient.GetQRCodeResult()
			if err != nil {
				fmt.Printf("err: %v\n", err)
				return
			}
			if retCode.Waitable() {
				time.Sleep(3 * time.Second)
				continue
			}
			if !retCode.Success() {
				fmt.Printf("retCode.Name(): %v\n", retCode.Name())
				return
			}
			break
		}
		_, err = qq.QQClient.QRCodeLogin()
		fmt.Printf("err: %v\n", err)
		return
	}()

	for {
		_, err := os.Stat("qrcodePath")
		if err != nil {
			time.Sleep(time.Second)
			continue
		} else {
			break
		}
	}

	// Redirect to the QR code image page.
	w.Header().Set("Location", "/img")
	w.WriteHeader(http.StatusFound)
}

简单代码。。 
close 后
login ，出现  FetchQRCodeDefault err: Packet timed out

**Comment by Redmomn** [comment]
你起一个新的client试试

**Comment by ckikoo** [comment]
new 一个新的可以 ， 大概有可能是缓存的问题
