### ISSUE TITLE
目前只能扫码嘛  后续是不是无望密码登录了

### ISSUE THREAD

**Issue by yaoyaochil** [LagrangeDev/LagrangeGo#22]
盯一波

**Comment by Redmomn** [comment]
目前的打算是只维护扫码登录

**Comment by yaoyaochil** [comment]
[login]: Login fail on oicq (2d): [禁止登录]>[登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。]
login fail on oicq (2d): [禁止登录]>[登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。]

你好 像出现这种  是不是需要我签名 还是什么

**Comment by Redmomn** [comment]
需要配签名服务器，在lagrange.core的readme里有写

**Comment by yaoyaochil** [comment]
好的谢谢
