### ISSUE TITLE
[Bug] GroupMemberLeaveEvent 的 OperatorUid 解析错误

### ISSUE THREAD

**Issue by Szzrain** [LagrangeDev/LagrangeGo#25]
被踢出群返回的 OperatorUid 似乎不是正常的 Uid 格式并且无法通过缓存找到 Uin
与其他的正常返回的 OperatorUid 进行对比:
禁言事件返回的 OperatorUid:
```
u_ulFxYKDM9BuGiWlf9_UGDw
```
踢出事件返回的 OperatorUid:
```

X
u_ulFxYKDM9BuGiWlf9_UGDw    Ա 0*08b16d77d4517427eb047c61447e3bb930ddd70eb63ccc199
```
我注意到正确的 Uid 包含在这段字符串内，可能是什么地方没有被正确解析？但是我对比了一下C#版本的代码没有发现问题在什么地方

**Comment by Redmomn** [comment]
现在应该是修好了

**Comment by Szzrain** [comment]
经过测试已经修复成功
