### ISSUE TITLE
关于许可证问题及其解决办法

### ISSUE THREAD

**Issue by fumiama** [LagrangeDev/LagrangeGo#28]
### 说明
注意到本项目有多处借鉴了 [MiraiGo](https://github.com/Mrs4s/MiraiGo) 的代码，现就此向贵方提出如下要求：

1. 在 README 中注明此项目借鉴了 [MiraiGo](https://github.com/Mrs4s/MiraiGo)。
2. 在源代码中所有来源为 [MiraiGo](https://github.com/Mrs4s/MiraiGo) 的位置使用注释方式标明出处。
  - 例1：
  https://github.com/LagrangeDev/LagrangeGo/blob/abba4c7876537601447fe3a232cc81eba4fbcae7/utils/proto/wrapper.go#L1-L32
  中，添加
    ```go
    package proto
    
    // from https://github.com/Mrs4s/MiraiGo/blob/master/internal/proto/wrapper.go
    
    import (
	    "reflect"
    
	    "google.golang.org/protobuf/types/known/anypb"
    
	    "github.com/RomiChan/protobuf/proto"
    )
    
    // TODO: move to a new package
    const debug = false
    
    ...
    ```
  - 例2：
  https://github.com/LagrangeDev/LagrangeGo/blob/abba4c7876537601447fe3a232cc81eba4fbcae7/client/event.go#L1-L32
  中，添加
    ```go
    package client

    // from https://github.com/Mrs4s/MiraiGo/blob/master/client/events.go

    import (
	    "reflect"
	    "runtime/debug"
	    "sync"
    
	    "github.com/LagrangeDev/LagrangeGo/event"
	    "github.com/LagrangeDev/LagrangeGo/message"
    
	    "github.com/LagrangeDev/LagrangeGo/utils"
    )
    
    var eventLogger = utils.GetLogger("event")
    ```
  - 如果遇到一个文件中部分借鉴的情况，请分别在相应位置注明。
3. 由于 [MiraiGo](https://github.com/Mrs4s/MiraiGo) 所使用的 [GNU Affero General Public License v3.0](https://github.com/Mrs4s/MiraiGo/blob/master/LICENSE) 协议的传染性，贵方需要将此仓库协议从 GPLv3 变更为 AGPLv3。

### 其它解决方式
贵方也可选择完全删除仓库中与 [MiraiGo](https://github.com/Mrs4s/MiraiGo) 相同或相似的代码，这样便可不必执行上述要求。

**Comment by TheSnowfield** [comment]
> 贵方也可选择完全删除仓库中与 [MiraiGo](https://github.com/Mrs4s/MiraiGo) 相同或相似的代码，这样便可不必执行上述要求。
換血重寫不合實際，淨室開發原則已經被破壞。目前來看比較好的做法是刪除，或者加上署名以及更換license。

**Comment by TheSnowfield** [comment]
> 1. 在 README 中注明此项目借鉴了 [MiraiGo](https://github.com/Mrs4s/MiraiGo)。

甚至連項目的readme都是一樣的格式

**Comment by Szzrain** [comment]
原来如此，我就说这个项目里有些代码怎么看着有点奇怪，注明版权信息和更换License的事情还是由 @Redmomn 来处理吧

**Comment by Redmomn** [comment]
感谢指正，抄代码不注明来源确实不对，非常抱歉，此issue和其他借鉴代码的部分将在今天内处理完成

**Comment by fumiama** [comment]
感谢贵方负责任的态度，我已确实看到了仓库的更改，因此我将关闭此issue。希望与贵方一道，将开源精神保持并传承下去🤝
