### ISSUE TITLE
不支持“扩展API-上传群文件”？

### ISSUE THREAD

**Issue by oddfar** [LagrangeDev/LagrangeGo#54]
在 https://github.com/LagrangeDev/go-cqhttp 项目中

```go
// TODO 不支持的api，扔了先
// CQUploadGroupFile 扩展API-上传群文件
………………
```

这块不支持，是协议本身不支持，还是没接过去
如果是没接过去，我需要怎么做？请指点一下

**Comment by Redmomn** [comment]
协议是支持的，只是这个功能在此项目还未实现

**Comment by Redmomn** [comment]
参考https://github.com/LagrangeDev/Lagrange.Core/tree/master/Lagrange.Core/Internal/Service/Action
这里面，对应此项目的client/packets/oidb
好像没有文件上传？
另外lagrange.core用了很多继承类并且没有直接引用，可能不太好理解

**Comment by Redmomn** [comment]
刚刚发现lagrange.core有上传群文件，后续会补上

**Comment by oddfar** [comment]
> 刚刚发现lagrange.core有上传群文件，后续会补上

看到了，[GroupFSDownloadService](https://github.com/LagrangeDev/Lagrange.Core/blob/master/Lagrange.Core/Internal/Service/Action/GroupFSDownloadService.cs)，我试试看能不能补上

**Comment by oddfar** [comment]
尝试了写下群文件类操作：https://github.com/LagrangeDev/Lagrange.Core/blob/master/Lagrange.OneBot/Core/Operation/File
这块有点不好理解，改造失败

然后试着`创建群文件文件夹`：`[Service("OidbSvcTrpcTcp.0x6d7_0")]`
这块却出现 `安全检查未通过` 问题
**请问您这边计划什么时候补上？**
<img width="873" alt="image" src="https://github.com/user-attachments/assets/0484a890-2d2f-472c-9d49-ac309344f2c8">

GroupFSCreateFolder.go
```go
package oidb

import (
	"github.com/LagrangeDev/LagrangeGo/client/packets/pb/service/oidb"
)

func BuildGroupFSCreateFolderReq(groupUin uint32, folderName string) (*OidbPacket, error) {
	body := &oidb.OidbSvcTrpcTcp0X6D7_0{
		Folder: &oidb.OidbSvcTrpcTcp0X6D7_0Folder{
			GroupUin:      groupUin,
			RootDirectory: "/",
			FolderName:    folderName,
		},
	}

	return BuildOidbPacket(0x6D7, 0, body, false, true)
}

func ParseGroupFSCreateFolderResp(data []byte) error {
	return CheckError(data)
}
```

OidbSvcTrpcTcp0x6D7_0.proto
```proto
syntax = "proto3";

option go_package = "github.com/LagrangeDev/LagrangeGo/client/packets/pb/service/oidb";

message OidbSvcTrpcTcp0x6D7_0 {
  OidbSvcTrpcTcp0x6D7_0Folder Folder = 1;
}

message OidbSvcTrpcTcp0x6D7_0Folder {
  uint32 GroupUin = 1;
  string RootDirectory = 3;
  string FolderName = 4;
}
```

**Comment by Redmomn** [comment]
尝试换一下上传的文件，这个应该是tx对上传的文件进行扫描

**Comment by pk5ls20** [comment]
@oddfar 
我稍晚点会补下群文件上传和私聊文件上传
但是截至目前，[Lagrange.Core](https://github.com/LagrangeDev/Lagrange.Core) 的文件上传也有问题（ https://github.com/LagrangeDev/Lagrange.Core/issues/503 ），我能做到的只有同步上游[Lagrange.Core](https://github.com/LagrangeDev/Lagrange.Core) 的实现逻辑（以及后续修复）到这里😂

**Comment by oddfar** [comment]
> @oddfar 我稍晚点会补下群文件上传和私聊文件上传 -> #72 但是截至目前，[Lagrange.Core](https://github.com/LagrangeDev/Lagrange.Core) 的文件上传也有问题（ [LagrangeDev/Lagrange.Core#503](https://github.com/LagrangeDev/Lagrange.Core/issues/503) ），我能做到的只有同步上游[Lagrange.Core](https://github.com/LagrangeDev/Lagrange.Core) 的实现逻辑（以及后续修复）到这里😂

大佬牛逼，这块实现逻辑有了就够用了，后续我可以根据上游的git记录来修复
