### ISSUE TITLE
登录之后获取Cookie

### ISSUE THREAD

**Issue by xiaomo489** [LagrangeDev/LagrangeGo#59]
请问一下，登录之后如何获取Cookie呢？

**Comment by Redmomn** [comment]
目前没有这个功能

**Comment by 2mf8** [comment]
> Cookie

获取这个是用于快速登陆吗？还是访问一些网页？

**Comment by 2mf8** [comment]
> 请问一下，登录之后如何获取Cookie呢？

快速登陆是可以的

**Comment by xiaomo489** [comment]
> > Cookie
> 
> 获取这个是用于快速登陆吗？还是访问一些网页？

访问网页呢

**Comment by Redmomn** [comment]
已支持获取cookies
