### ISSUE TITLE
大佬， 为什么群聊消息好像没发送出去？？

### ISSUE THREAD

**Issue by ckikoo** [LagrangeDev/LagrangeGo#61]
qqclient.GroupMessageEvent.Subscribe(func(client *client.QQClient, event *message.GroupMessage) {
		_, err := client.SendGroupMessage(event.GroupUin, []message.IMessageElement{&message.TextElement{Content: "2"}})
		fmt.Printf("err: %v\n", err)
	})
	
	还有对于文档  https://github.com/LagrangeDev/LagrangeGo/blob/master/docs/examples/index.md
	qqclient.GroupMessageEvent.Subscribe(func(client *client.QQClient, event *message.GroupMessage) {
		if event.ToString() == "114514" {
			img, _ := os.ReadFile("testgroup.png")
			_, err := client.SendGroupMessage(event.GroupCode, []message.IMessageElement{&message.GroupImageElement{Stream: img}})
			if err != nil {
				return
			}
		}
		GroupCode 这个字段我没有找到是否需要更新一下demo文档？

**Comment by Redmomn** [comment]
GroupCode已更新为GroupUin

**Comment by Redmomn** [comment]
另外这个示例是发送图片，你的工作目录需要有testgroup.png这张图片

**Comment by Redmomn** [comment]
关于demo，可以直接看main.go，最近在大量加新功能，文档更新不及时

**Comment by ckikoo** [comment]
好像问题出在：在手机上创建不是按分类的小群是不被支持。
