### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by suhang12332** [LagrangeDev/LagrangeGo#74]
<img width="825" alt="image" src="https://github.com/user-attachments/assets/0c8d3319-3118-4f2d-8221-6ef967b7bf43">
<img width="499" alt="image" src="https://github.com/user-attachments/assets/a5278166-77f5-4fa6-8762-6db33a869ed2">

**Comment by suhang12332** [comment]
<img width="1394" alt="image" src="https://github.com/user-attachments/assets/95b1937b-5c38-47d8-83c6-f801c6a1861e">
<img width="469" alt="image" src="https://github.com/user-attachments/assets/8a3d8eb6-223f-4f78-9fb2-5e46201e51ba">

**Comment by Redmomn** [comment]
确认你用的签名是哪个版本的

**Comment by suhang12332** [comment]
<img width="756" alt="image" src="https://github.com/user-attachments/assets/9510d76a-e1c0-4e7f-827d-98394e45497d">

**Comment by suhang12332** [comment]
我该怎么确认签名版本

**Comment by Redmomn** [comment]
这个就是13107的

**Comment by suhang12332** [comment]
![48D94533-670F-4FEB-8F37-412738F86D71](https://github.com/user-attachments/assets/2c3cab76-a4c7-4fcd-a4ec-c68cecb2970f)

**Comment by suhang12332** [comment]
这两个版本 我都尝试过,都无法登录

**Comment by Redmomn** [comment]
这行，稍晚一会我看看怎么个事

**Comment by suhang12332** [comment]
好的 万分感谢 我在napcatqq中看到 
<img width="651" alt="image" src="https://github.com/user-attachments/assets/ec19dc45-8ba9-41ad-b969-0098de442788">
3.2.12-26702

**Comment by suhang12332** [comment]
不知道是否对您有帮助

**Comment by suhang12332** [comment]
<img width="763" alt="image" src="https://github.com/user-attachments/assets/0530f77e-b1ef-49ef-9551-0a072d4b7570">

**Comment by Redmomn** [comment]
跟这个没关系，光有版本号并不能说明什么

**Comment by suhang12332** [comment]
好的 麻烦大佬闲了看下

**Comment by Redmomn** [comment]
刚刚没细看你这个，第二个截图配置没有问题，应该是qq低版本导致的，换linux25765版本，sign后面加个/25765就行

**Comment by suhang12332** [comment]
我试试

**Comment by suhang12332** [comment]
https://sign.lagrangecore.org/api/sign/25765 签名是填这个?

**Comment by Redmomn** [comment]
对，已经更新到文档了

**Comment by suhang12332** [comment]
登陆错误: all sign service down
<img width="836" alt="image" src="https://github.com/user-attachments/assets/b729a903-2e0c-40ac-a3f2-439940524ce0">

**Comment by suhang12332** [comment]
<img width="941" alt="image" src="https://github.com/user-attachments/assets/48abdae6-18c9-4ca6-881b-7ac64675a6cf">

**Comment by suhang12332** [comment]
更改签名地址后,也无法登录

**Comment by suhang12332** [comment]
看到你的提交了,已经成功了

**Comment by suhang12332** [comment]
@2mf8 代码貌似没合全

**Comment by Redmomn** [comment]
406ca67910ef8b462996df97c207d8899d1e9e03
