### ISSUE TITLE
@的事件的使用

### ISSUE THREAD

**Issue by ckikoo** [LagrangeDev/LagrangeGo#91]
qq.QQClient.SendGroupMessage(11111, []message.IMessageElement{message.NewAt(uint32(qqNumber), []string{msg}...)})
大佬这个为什么效果只显示@用户， 然后 msg没有看到？

**Comment by Redmomn** [comment]
我这实测图文混排并没有问题
```
img, _ := message.NewFileImage("testgroup.png")
_, err := c.SendGroupMessage(event.GroupUin, []message.IMessageElement{message.NewAt(event.Sender.Uin), message.NewText("114514"), img})
if err != nil {
    logger.Error(err)
}
```
![image](https://github.com/user-attachments/assets/e49bf77d-0814-497f-bf4c-cdee6adcfc64)

有问题请附上完整的代码以及效果截图

**Comment by ckikoo** [comment]
方法使用错了。。。。。。。

**Comment by ckikoo** [comment]
感谢
