### ISSUE TITLE
[提问] 处理好友邀请进群的方法找不到

### ISSUE THREAD

**Issue by ckikoo** [LagrangeDev/LagrangeGo#98]
我翻遍了QQClient下的 所有以gr开头的函数，并没有找到

**Comment by Redmomn** [comment]
`SetGroupRequest`就是
需要配合`GetGroupSystemMessages`使用
详情参考https://github.com/LagrangeDev/go-cqhttp/blob/0e764e125947b7c65bc8c598cb4e9330a82f0293/coolq/api.go#L885
